[build]
  base = "/"
  publish = "src/"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/oembed"
  to = "/oembed.json"
  status = 200
  force = true
  headers = {Content-Type = 'application/json'}

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  headers = {Content-Type = 'application/xml'}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
  